@startuml
!theme plain

start

:Прочитать тело запроса;

if (Удалось прочитать?) then (да)
    :Десериализовать JSON в переменную reqTask;
    if (Удалось десериализовать?) then (да)
        :Проверить, что поле task.Title не пустое
    else (нет)
    :Возврат ошибки 400;
    endif   

else (нет)
    :Возврат ошибки 400;
endif



end

@enduml